export default {
	async fetch(request) {
	  const html = `<!DOCTYPE html>
	  <body>
		<h1>Painel de Controle</h1>
		<p>This markup was generated by a Cloudflare Worker.</p>
		<script>
		  const password = prompt("Please enter the admin password:");
		  if (password !== "${ADMIN_PASSWORD}") {
			alert("Incorrect password!");
			document.body.innerHTML = "<h1>Access Denied</h1>";
		  }
		</script>
	  </body>
	  `;
  
	  return new Response(html, {
		headers: {
		  "content-type": "text/html;charset=UTF-8",
		},
	  });
	},
  };