name="larineconsultoria"
pages_build_output_dir = "./"
kv_namespaces = [
  { binding = "larineconsultoria", id = "255c8083680646568fce835bbbdfdef7" }
]
[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAAA4oB5jRR9gAVTs2p50_SWvfeds"
RESEND_API_KEY = "re_DdQ9XQPv_Kp7b9AcNR95tYtcZ4E6hBWac"