name = "larineconsultoria-worker"
compatibility_date = "2025-01-03"

[vars]
STRIPE_SECRET_KEY = "sk_test_51QdDLzBmLhzPvPbKglzZmKrVcOuW7d4NgyOKngDkB0FptyY1yTC10rpgqm1lTXZ1IVJyVwCYVyV3JculRxSWSvA100Tqt65jWb"
STRIPE_WEBHOOK_SECRET = "whsec_xBNJUZOxfCijLSbL7EbtmIFRrFPwuAXd"

[build]
command = ""
pages_build_output_dir = "./public"
